### ISSUE TITLE
Can it be made into the form of a theme?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardSkills/OrchardSkills.OrchardCore.BlazorWASM#1]
Can it be made into the form of a theme?

**Comment by OrchardSkills** [comment]
Not an Orchard Core Theme. Blazor is a Component Model Architecture were as Orchard Core is Model View Controller Architecture.  Just think as the Blazor WebAssembly application being just like JavaScript. You can create a Theme inside of a Blazor App. You can also build components.
